/*****************************************************************************************************
* This code was generated by a tool.                                                                 *
* Generated 2016-08-29 02:19:08 from AssemblyInfo.tt                                                 *
*                                                                                                    *
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.     *
*****************************************************************************************************/

using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("KBL.Extensions")]
[assembly: AssemblyDescription("Class extension methods for Double, IEnumerable, Array, String, DateTime, Assembly")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
// [assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("Kilo Bravo")]
[assembly: AssemblyProduct("PhysicalMeasure")]
[assembly: AssemblyCopyright("Copyright © 2015-2016 Kilo Bravo")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]


// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("7139b888-5ce1-4604-b2e8-19fd45bc8b0e")]

//  Build at  2016-08-29 02:19:08 2016-08-29 02:10:00
//  major:    1
//  minor:    0
//  build:    6085
//  revision: 3900

[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyFileVersion("1.0.6085.3900")]
[assembly: AssemblyInformationalVersion("1.0.6085.3900")]


